leftnav:
- identifier: 66b08c03-2ea2-4bf4-97db-7afc35d286e5
  name: Main Menu
  url: /pages/homepage
  weight: 10
- identifier: a0ec1996-9829-47b0-9e8c-b088a7c7c42b
  name: Video Resource
  url: /pages/video-resources
  weight: 20
